name: Trigger auto deployment for testbackend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/testbackend-AutoDeployTrigger-f79c2d94-ae34-45a9-8151-232e6f7fb3f5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.TESTBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTBACKEND_REGISTRY_PASSWORD }}
          containerAppName: testbackend
          resourceGroup: DefaultResourceGroup-NEU
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


